---
name: Lint
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint yamllint

      - name: Run Pylint
        run: |
          pylint ./micropython

      - name: Run yamllint
        run: |
          yamllint .
